/* Replace with your SQL commands */
LOCK TABLES `items` WRITE;
INSERT INTO `items` VALUES (1,1,'Silavent/Domus SDF100 100mm 4" Extractor Fan Standard','Silavent/Domus SDF100 100mm 4" Extractor Fan Standard Timer Model 80 m3/hr Humidity Pull Cord Model Application: Bathroom and toilet Key features: Provide effective levels of ventilation Modern fascia for discreet integration within the bathroom or toilet Extract rates to meet 2010 Building Regulation requirements', 'https://i.ebayimg.com/images/g/TSQAAOSwclhd-jY2/s-l1600.jpg', 26, 'active'),
(2,1,'Apple iPhone XR - 64GB/128/256GB','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure', 'https://dl.dropboxusercontent.com/s/y9cf6zmxk6m4fqn/XR.png', 258, 'active'),
(3,1,'Nextbase 522GW Dash Cam In-Car 1440p Ultra HD WiFi GPS Bluetooth Alexa','The Nextbase 522GW is packed with great features including 1440p HD recording at 30fps, a 140-degree viewing angle, 2.5" high resolution touch-screen, and a Polarising Filter lens to reduce windscreen glare and record clearer, enhanced images. Innovative new features alo include Built-In Alexa, QuickLink Wi-Fi, 4.2 Bluetooth, GPS 10x Module, SOS Emergency, a high precision G Sensor and Intelligent Parking Mode. The 522GW allows you to connect add-on module cams for rear recording. The 522GW also includes the new and exclusive Click&Go PRO powered car mount, which makes the dash cam to be completely wire-free and able to be removed easily from your vehicle.','https://i.ebayimg.com/images/g/la0AAOSwI~dgWbgt/s-l500.jpg',50,'active'),
(4,1,'Simba Mattress Certified Refurbished', 'We know it can be a bit of a snooze reading small print, so we’ve summarised some of the main points people ask us about below. But it’s important to note this is a summary only and does not replace the full terms and conditions, which can be read under the tab "Guarantee T&Cs".','https://i.ebayimg.com/images/g/H5IAAOSwoOZfFvw5/s-l1600.jpg', 100, 'active'),
(5,3,'Joules Womens 211148 Half Zip Sweatshirt', 'For all manner of outdoor activities, this brushback cotton sweatshirt is a real box-ticker. The funnel neck is perfect for snuggling into and the curved hem creates a more fitted finish.','https://cdn.joules.com/medias/?context=bWFzdGVyfGNkbnwxNjY5MDV8aW1hZ2UvanBlZ3xzeXMtbWFzdGVyL2Nkbi9oM2QvaDI5LzEwMDI1ODgyNzc5Njc4fDNjNjcyMzI3Nzg2NTVhOWNlNGU4OTU1MDNlYzg3MDM0MWNmMzAyNjE2MGFkMDgyYTQzODcxNjYzMWFkMWQxZGQ',12,'active'),
(6,3,'Womens New Balance 515 Lightweight Cushioned Trainers in Black', 'If you haven?t yet heard of Getthelabel.com, where have you been? Were the ultimate website for essential and indispensable designer clothing and footwear, and our team is dedicated to offering our customers the best prices when it comes to fashion. It all began in 2009 when we became a subsidiary of JD Sports Fashion plc. We started with a range. And we?re still growing, so watch this space! We offer knockout prices and unbelievable discounts on iconic labels. With over 7,000 items online and up to 75% off RRP.', 'https://s3-eu-west-1.amazonaws.com/images.linnlive.com/b75d2d26681492eb62097e0394d8fe8c/06e1bc76-473a-486c-b018-e7de5635094b.jpg', 16,'active'),
(7,3,'Dewalt DWS520KT Plunge Cut Circular Saw', 'Dewalt DWS520KT Plunge Saw and Guide Rail, complete with 48 tooth saw blade, 2 x 1.5m guide rail with connectors, carry bag and carrying case. Dewalt offer a simple and effective solution to a wide range of applications including laminate cutting and door trimming. Extremely high levels of accuracy, finish and durability make the DWS520KT a desireable product. Dewalt DWS520KT plunge saw from Dewalt gives outstanding levels of accuracy and finish, as well as extreme durability. The DWS520KT is designed in conjunction with guide rails that are easy to set up and use, the system offers a simple and effective solution for a range of applications, particularly with laminate cutting. The Dewalt DWS520KT has a flat outside guard so can be used for door trimming. Anti kickback function stops the saw from moving backwards along the rail.','https://i.ebayimg.com/images/g/nJcAAOSwDtxgYsQM/s-l1600.jpg',210,'active'),
(8,2,'Folding Bike Viking Metropolis 20" Wheel 6 Speed Folder Bicycle White', 'First established in Wolverhampton in 1908 the Viking brand has a history, rich in the tradition of top quality road bikes throughout the century. Quality, style and durability have always been the hallmarks of Viking cycles. Todays Vikings still embody those core qualities, as cycling in the UK has developed Viking has looked to widen its range to meet demands of modern cyclists. Now designed in Manchester the 2018 Viking range includes Road, Gravel, Fixed Wheel, Hybrid, Heritage, Electric Bikes, Folders and Tandems.', 'https://i.ebayimg.com/images/g/6LgAAOSwSMRgSKxi/s-l1600.jpg', 321, 'active'),
(9,2,'Shimano Cycling Jersey Team Long Sleeve Purple Red All Sizes', 'We use Royal Mail for the majority of our orders due to their reliable service and proven track record. Please see below for Royal Mails suggested delivery times regarding the services we use (these are guidelines and times may vary depending on your geographical location within the UK).', 'https://i.ebayimg.com/images/g/CZgAAOSwu1dgIUi4/s-l500.jpg', 142, 'active');

UNLOCK TABLES;